import test from 'node:test';
import assert from 'node:assert/strict';
import { analyzeLink,automaticReferences,normalizeDomain,domainOf } from '../src/engine.js';
const check=(href,text='https://ligdna.com/login',extra={})=>analyzeLink({href,text,...extra});
const ids=result=>result.findings.map(f=>f.id);
test('finds the user example without a registered domain',()=>{const r=check('https://ligdaa.com/login');assert.equal(r.level,'danger');assert.ok(ids(r).includes('TYPO'));assert.ok(ids(r).includes('MISMATCH'));});
test('does not need a display URL to compare with the current corporate site',()=>{const r=check('https://ligdaa.com','로그인',{baseUrl:'https://mail.ligdna.com/inbox'});assert.ok(ids(r).includes('TYPO'));});
test('normal label is not interpreted as a URL mismatch',()=>{assert.equal(check('https://ligdna.com','문서 열기').level,'clear');});
test('ordinary document filename is not misread as a displayed domain',()=>{assert.equal(check('https://ligdna.com/report.pdf','report.pdf').level,'clear');});
test('case and legitimate subdomains do not create mismatches',()=>{assert.equal(check('https://docs.ligdna.com/report','https://LIGDNA.com/report').level,'clear');});
test('separates hostile subdomain from the actual registrable domain',()=>{const r=check('https://ligdna.com.verify.example/login');assert.equal(r.domain,'verify.example');assert.ok(ids(r).includes('SUBDOMAIN'));});
test('catches username deception',()=>{const r=check('https://ligdna.com@verify.example');assert.equal(r.hostname,'verify.example');assert.ok(ids(r).includes('USERINFO'));});
test('catches a Cyrillic homoglyph and preserves the actual URL',()=>{const r=check('https://lіgdna.com');assert.ok(ids(r).includes('HOMOGLYPH'));assert.match(r.url,/xn--/);});
test('known service typo works without setup',()=>{assert.ok(ids(check('https://micros0ft.com','문서 열기')).includes('HOMOGLYPH'));});
test('TLD swaps are a caution signal, without claiming maliciousness',()=>{const r=check('https://ligdna.net','로그인',{protectedDomains:['ligdna.com']});assert.equal(r.level,'caution');assert.ok(ids(r).includes('BRAND'));});
test('detects a trusted domain in a path',()=>{assert.ok(ids(check('https://evil.example/ligdna.com/login','로그인',{protectedDomains:['ligdna.com']})).includes('PATH'));});
test('short URLs are unverified, not definitively malicious',()=>{const r=check('https://bit.ly/demo','문서 열기');assert.equal(r.level,'caution');assert.deepEqual(ids(r),['REDIRECT']);});
test('known wrapper is decoded locally and the original wrapper is retained',()=>{const url='https://tenant.safelinks.protection.outlook.com/?url=https%3A%2F%2Fligdna.com%2Flogin&data=test';const r=check(url);assert.equal(r.level,'clear');assert.equal(r.url,url);assert.equal(r.targetUrl,'https://ligdna.com/login');assert.equal(r.wrapped,true);});
test('known wrapper does not hide a dangerous embedded URL',()=>{assert.ok(ids(check('https://tenant.safelinks.protection.outlook.com/?url=https%3A%2F%2Fligdaa.com')).includes('TYPO'));});
test('fake wrapper hosts cannot suppress a mismatch',()=>{const r=check('https://safelinks.protection.outlook.com.evil.example/?url=https%3A%2F%2Fligdna.com');assert.equal(r.wrapped,false);assert.ok(ids(r).includes('MISMATCH'));});
test('an arbitrary redirect parameter is not assumed to be the final destination',()=>{const r=check('https://example.org/go?url=https%3A%2F%2Fligdna.com');assert.equal(r.hostname,'example.org');assert.equal(r.wrapped,false);assert.ok(ids(r).includes('REDIRECT'));});
test('PSL handles co.kr and private hosting tenants',()=>{assert.equal(domainOf('mail.company.co.kr'),'company.co.kr');assert.notEqual(domainOf('alice.github.io'),domainOf('bob.github.io'));});
test('relative URLs resolve against the actual base',()=>{assert.equal(check('/news','문서 열기',{baseUrl:'https://ligdna.com/inbox'}).url,'https://ligdna.com/news');});
test('unsafe schemes are not treated as a regular webpage',()=>{assert.equal(check('javascript:alert(1)','확인').level,'caution');assert.equal(check('mailto:team@example.com','회신').level,'ignored');});
test('no-op JavaScript links used by editor controls are ignored',()=>{for(const href of ['javascript:void(0);','javascript: void ( 0 ) ;','javascript:void 0','javascript:;'])assert.equal(check(href,'링크 수정').level,'ignored');assert.equal(check('javascript:void(openDocument())','열기').level,'caution');});
test('normal known regional domains do not trigger other built-in references',()=>{assert.equal(check('https://google.co.kr','검색').level,'clear');});
test('normalization rejects malformed references',()=>{for(const value of ['com','https://evil.com@ligdna.com','https://ligdna.com/path','foo..com','127.0.0.1'])assert.equal(normalizeDomain(value),null);assert.equal(normalizeDomain('LIGDNA.com'),'ligdna.com');});
test('malformed input does not crash',()=>{assert.equal(check('http://[').level,'unknown');assert.doesNotThrow(()=>check('https://evil.example/%xx',''));});
test('automatic references include the corporate domain but not localhost',()=>{assert.ok(automaticReferences('https://mail.ligdna.com').includes('ligdna.com'));assert.ok(!automaticReferences('http://localhost:4173').includes('localhost'));});
